WITH _temp_view_1 AS (
SELECT /*+ materialize */ sum((F0."l_extendedprice" * (1 - F0."l_discount"))) AS "AGGR_0", F0."l_orderkey" AS "GROUP_0", F0."o_orderdate" AS "GROUP_1", F0."o_shippriority" AS "GROUP_2"
FROM (
SELECT F0."l_orderkey" AS "l_orderkey", F0."l_partkey" AS "l_partkey", F0."l_suppkey" AS "l_suppkey", F0."l_linenumber" AS "l_linenumber", F0."l_quantity" AS "l_quantity", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_tax" AS "l_tax", F0."l_returnflag" AS "l_returnflag", F0."l_linestatus" AS "l_linestatus", F0."l_shipdate" AS "l_shipdate", F0."l_commitdate" AS "l_commitdate", F0."l_receiptdate" AS "l_receiptdate", F0."l_shipinstruct" AS "l_shipinstruct", F0."l_shipmode" AS "l_shipmode", F0."l_comment" AS "l_comment", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F1."c_custkey" AS "c_custkey", F1."c_name" AS "c_name", F1."c_address" AS "c_address", F1."c_nationkey" AS "c_nationkey", F1."c_phone" AS "c_phone", F1."c_acctbal" AS "c_acctbal", F1."c_mktsegment" AS "c_mktsegment", F1."c_comment" AS "c_comment"
FROM ((
SELECT F0."l_orderkey" AS "l_orderkey", F0."l_partkey" AS "l_partkey", F0."l_suppkey" AS "l_suppkey", F0."l_linenumber" AS "l_linenumber", F0."l_quantity" AS "l_quantity", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_tax" AS "l_tax", F0."l_returnflag" AS "l_returnflag", F0."l_linestatus" AS "l_linestatus", F0."l_shipdate" AS "l_shipdate", F0."l_commitdate" AS "l_commitdate", F0."l_receiptdate" AS "l_receiptdate", F0."l_shipinstruct" AS "l_shipinstruct", F0."l_shipmode" AS "l_shipmode", F0."l_comment" AS "l_comment", F1."o_orderkey" AS "o_orderkey", F1."o_custkey" AS "o_custkey", F1."o_orderstatus" AS "o_orderstatus", F1."o_totalprice" AS "o_totalprice", F1."o_orderdate" AS "o_orderdate", F1."o_orderpriority" AS "o_orderpriority", F1."o_clerk" AS "o_clerk", F1."o_shippriority" AS "o_shippriority", F1."o_comment" AS "o_comment"
FROM ((
SELECT F0."l_orderkey" AS "l_orderkey", F0."l_partkey" AS "l_partkey", F0."l_suppkey" AS "l_suppkey", F0."l_linenumber" AS "l_linenumber", F0."l_quantity" AS "l_quantity", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_tax" AS "l_tax", F0."l_returnflag" AS "l_returnflag", F0."l_linestatus" AS "l_linestatus", F0."l_shipdate" AS "l_shipdate", F0."l_commitdate" AS "l_commitdate", F0."l_receiptdate" AS "l_receiptdate", F0."l_shipinstruct" AS "l_shipinstruct", F0."l_shipmode" AS "l_shipmode", F0."l_comment" AS "l_comment"
FROM "lineitem" AS F0
WHERE (((((((((((F0."l_orderkey" >= 492121) AND (F0."l_orderkey" < 492181)) OR ((F0."l_orderkey" >= 993594) AND (F0."l_orderkey" < 993655))) OR ((F0."l_orderkey" >= 1188282) AND (F0."l_orderkey" < 1188342))) OR ((F0."l_orderkey" >= 2300051) AND (F0."l_orderkey" < 2300112))) OR ((F0."l_orderkey" >= 2435655) AND (F0."l_orderkey" < 2435718))) OR ((F0."l_orderkey" >= 2456376) AND (F0."l_orderkey" < 2456433))) OR ((F0."l_orderkey" >= 2628147) AND (F0."l_orderkey" < 2628204))) OR ((F0."l_orderkey" >= 3459775) AND (F0."l_orderkey" < 3459838))) OR ((F0."l_orderkey" >= 4877963) AND (F0."l_orderkey" < 4878023))) OR ((F0."l_orderkey" >= 5521724) AND (F0."l_orderkey" < 5521792)))) F0 CROSS JOIN (
SELECT F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment"
FROM "orders" AS F0
WHERE (((((((((((F0."o_orderkey" >= 492116) AND (F0."o_orderkey" < 492174)) OR ((F0."o_orderkey" >= 993600) AND (F0."o_orderkey" < 993658))) OR ((F0."o_orderkey" >= 1188290) AND (F0."o_orderkey" < 1188348))) OR ((F0."o_orderkey" >= 2300022) AND (F0."o_orderkey" < 2300082))) OR ((F0."o_orderkey" >= 2435694) AND (F0."o_orderkey" < 2435754))) OR ((F0."o_orderkey" >= 2456388) AND (F0."o_orderkey" < 2456448))) OR ((F0."o_orderkey" >= 2628174) AND (F0."o_orderkey" < 2628232))) OR ((F0."o_orderkey" >= 3459768) AND (F0."o_orderkey" < 3459828))) OR ((F0."o_orderkey" >= 4877988) AND (F0."o_orderkey" < 4878048))) OR ((F0."o_orderkey" >= 5521728) AND (F0."o_orderkey" < 5521794)))) F1)) F0 CROSS JOIN (
SELECT F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment"
FROM "customer" AS F0
WHERE (((((((((((F0."c_custkey" >= 31651) AND (F0."c_custkey" < 31652)) OR ((F0."c_custkey" >= 32799) AND (F0."c_custkey" < 32805))) OR ((F0."c_custkey" >= 39166) AND (F0."c_custkey" < 39167))) OR ((F0."c_custkey" >= 49614) AND (F0."c_custkey" < 49620))) OR ((F0."c_custkey" >= 59619) AND (F0."c_custkey" < 59625))) OR ((F0."c_custkey" >= 69961) AND (F0."c_custkey" < 69962))) OR ((F0."c_custkey" >= 99159) AND (F0."c_custkey" < 99165))) OR ((F0."c_custkey" >= 106687) AND (F0."c_custkey" < 106688))) OR ((F0."c_custkey" >= 131386) AND (F0."c_custkey" < 131387))) OR ((F0."c_custkey" >= 140693) AND (F0."c_custkey" < 140694)))) F1)) F0
WHERE (((((F0."c_mktsegment" = 'BUILDING') and (F0."c_custkey" = F0."o_custkey")) and (F0."l_orderkey" = F0."o_orderkey")) and (F0."o_orderdate" < to_date('1995-03-15', 'YYYY-MM-DD'))) and (F0."l_shipdate" > to_date('1995-03-15', 'YYYY-MM-DD')))
GROUP BY F0."l_orderkey", F0."o_orderdate", F0."o_shippriority"),
_temp_view_0 AS (
SELECT /*+ materialize */ F0."GROUP_0" AS "l_orderkey", F0."AGGR_0" AS "revenue", F0."GROUP_1" AS "o_orderdate", F0."GROUP_2" AS "o_shippriority"
FROM (SELECT * FROM _temp_view_1) F0)
SELECT F0."l_orderkey" AS "l_orderkey", F0."revenue" AS "revenue", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority"
FROM (
SELECT F0."l_orderkey" AS "l_orderkey", F0."revenue" AS "revenue", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority"
FROM (SELECT * FROM _temp_view_0) F0
ORDER BY F0."revenue" DESC NULLS LAST, F0."o_orderdate" ASC NULLS LAST) F0
LIMIT 10;
